In [348]:
import pandas as pd
import numpy as np
data={
    'Age':[23,22,None,25,None],
    'Salary':[50000,None,45000,None,48000],
    'City':['Hyderabad','HYDERABAD','Mumbai','hyderabad','Pune'],
    'Experience':[5,2,3,5,3]        
}
df=pd.DataFrame(data)
print(df)

    Age   Salary       City  Experience
0  23.0  50000.0  Hyderabad           5
1  22.0      NaN  HYDERABAD           2
2   NaN  45000.0     Mumbai           3
3  25.0      NaN  hyderabad           5
4   NaN  48000.0       Pune           3

In [350]:
df.duplicated()
df.drop_duplicates()

    Age   Salary       City  Experience
0  23.0  50000.0  Hyderabad           5
1  22.0      NaN  HYDERABAD           2
2   NaN  45000.0     Mumbai           3
3  25.0      NaN  hyderabad           5
4   NaN  48000.0       Pune           3

In [352]:
df.isnull()

     Age  Salary   City  Experience
0  False   False  False       False
1  False    True  False       False
2   True   False  False       False
3  False    True  False       False
4   True   False  False       False

In [354]:
df.dropna()
df.dropna(axis=1)

        City  Experience
0  Hyderabad           5
1  HYDERABAD           2
2     Mumbai           3
3  hyderabad           5
4       Pune           3

In [356]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Salary'].fillna(df['Salary'].median(),inplace=True)
df['Experience'].fillna(df['Experience'].mode()[0],inplace=True)
print(df)

         Age   Salary       City  Experience
0  23.000000  50000.0  Hyderabad           5
1  22.000000  48000.0  HYDERABAD           2
2  23.333333  45000.0     Mumbai           3
3  25.000000  48000.0  hyderabad           5
4  23.333333  48000.0       Pune           3

C:\Users\swapn\AppData\Local\Temp\ipykernel_12540\4134771194.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)
C:\Users\swapn\AppData\Local\Temp\ipykernel_12540\4134771194.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].median(),inplace=True)
C:\Users\swapn\AppData\Local\Temp\ipykernel_12540\4134771194.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Experience'].fillna(df['Experience'].mode()[0],inplace=True)

In [358]:
df['City']=df['City'].str.upper()
print(df)

         Age   Salary       City  Experience
0  23.000000  50000.0  HYDERABAD           5
1  22.000000  48000.0  HYDERABAD           2
2  23.333333  45000.0     MUMBAI           3
3  25.000000  48000.0  HYDERABAD           5
4  23.333333  48000.0       PUNE           3

In [360]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df[['Age','Salary']]=scaler.fit_transform(df[['Age','Salary']])
print("Final Cleaned Data:\n")
print(df)

Final Cleaned Data:

        Age  Salary       City  Experience
0  0.333333     1.0  HYDERABAD           5
1  0.000000     0.6  HYDERABAD           2
2  0.444444     0.0     MUMBAI           3
3  1.000000     0.6  HYDERABAD           5
4  0.444444     0.6       PUNE           3