In [278]:
import pandas as pd
df=pd.read_csv('Book1.csv')
print(df)

      name  maths  science  english dept
0   Swapna     99       89       90   CS
1    Priya     98       90       80   IS
2  Karthik     90       87       94   EC
3  Manjula     94       83       79   IS
4   Thanga     78       88       72   AI
5     Anit     56       68       70   CS

In [308]:
df['total']=df[['maths','science','english']].sum(axis=1)
print(df)

      name  maths  science  english dept  total    Average    average
0   Swapna     99       89       90   CS    278  92.666667  92.666667
1    Priya     98       90       80   IS    268  89.333333  89.333333
2  Karthik     90       87       94   EC    271  90.333333  90.333333
3  Manjula     94       83       79   IS    256  85.333333  85.333333
4   Thanga     78       88       72   AI    238  79.333333  79.333333
5     Anit     56       68       70   CS    194  64.666667  64.666667

In [322]:
df['average']=df[['maths','science','english']].mean(axis=1)
print(df)

      name  maths  science  english dept  total    average
0   Swapna     99       89       90   CS    278  92.666667
1    Priya     98       90       80   IS    268  89.333333
2  Karthik     90       87       94   EC    271  90.333333
3  Manjula     94       83       79   IS    256  85.333333
4   Thanga     78       88       72   AI    238  79.333333
5     Anit     56       68       70   CS    194  64.666667

In [324]:
df.sort_values('total',ascending=False).head(3)[['name','total']]

      name  total
0   Swapna    278
2  Karthik    271
1    Priya    268

In [326]:
df.groupby('dept').mean(numeric_only=True)

      maths  science  english  total    average
dept
AI     78.0     88.0     72.0  238.0  79.333333
CS     77.5     78.5     80.0  236.0  78.666667
EC     90.0     87.0     94.0  271.0  90.333333
IS     96.0     86.5     79.5  262.0  87.333333

In [328]:
df.loc[(df[['maths','science','english']]>75).all(axis=1),'name']

0     Swapna
1      Priya
2    Karthik
3    Manjula
Name: name, dtype: object

In [330]:
df.isnull()

    name  maths  science  english   dept  total  average
0  False  False    False    False  False  False    False
1  False  False    False    False  False  False    False
2  False  False    False    False  False  False    False
3  False  False    False    False  False  False    False
4  False  False    False    False  False  False    False
5  False  False    False    False  False  False    False

In [332]:
df.isnull().sum()

name       0
maths      0
science    0
english    0
dept       0
total      0
average    0
dtype: int64