In [31]:
import pandas as pd
import numpy as np
data={
    'Name':['navya','arjun','riya','arjun',None],
    'Age':[23,25,None,25,22],
    'Salary':[50000,None,45000,60000,48000],
    'Department':['HR','IT','it','HR','it']
}
df=pd.DataFrame(data)
df.head()

    Name   Age   Salary Department
0  navya  23.0  50000.0         HR
1  arjun  25.0      NaN         IT
2   riya   NaN  45000.0         it
3  arjun  25.0  60000.0         HR
4   None  22.0  48000.0         it

In [33]:
df.isnull().sum()

Name          1
Age           1
Salary        1
Department    0
dtype: int64

In [35]:
df.dropna()
df.dropna(axis=1)

  Department
0         HR
1         IT
2         it
3         HR
4         it

In [48]:
df['Name'].fillna('Unknown',inplace=True)
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Salary'].fillna(df['Salary'].median(),inplace=True)
df['Department'].fillna(df['Department'].mode(),inplace=True)
print(df)

      Name    Age   Salary Department
0    navya  23.00  50000.0         HR
1    arjun  25.00  49000.0         IT
2     riya  23.75  45000.0         IT
3    arjun  25.00  60000.0         HR
4  Unknown  22.00  48000.0         IT

C:\Users\swapn\AppData\Local\Temp\ipykernel_14060\102551253.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)
C:\Users\swapn\AppData\Local\Temp\ipykernel_14060\102551253.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].median(),inplace=True)
C:\Users\swapn\AppData\Local\Temp\ipykernel_14060\102551253.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Department'].fillna(df['Department'].mode(),inplace=True)

In [39]:
df.duplicated()
df.drop_duplicates()

    Name    Age   Salary Department
0  navya  23.00  50000.0         HR
1  arjun  25.00  49000.0         IT
2   riya  23.75  45000.0         it
3  arjun  25.00  60000.0         HR
4   None  22.00  48000.0         it

In [41]:
df['Department']=df['Department'].str.upper()
print(df)

    Name    Age   Salary Department
0  navya  23.00  50000.0         HR
1  arjun  25.00  49000.0         IT
2   riya  23.75  45000.0         IT
3  arjun  25.00  60000.0         HR
4   None  22.00  48000.0         IT

In [46]:
print("Cleaned Dataset:")
print(df)

Cleaned Dataset:
      Name    Age   Salary Department
0    navya  23.00  50000.0         HR
1    arjun  25.00  49000.0         IT
2     riya  23.75  45000.0         IT
3    arjun  25.00  60000.0         HR
4  Unknown  22.00  48000.0         IT

Data Cleaning is a process to remove error,fixing inconsistency,standardizing formats,preparing raw data for analysis